# Seta cores
VERMELHO='\033[0;31m'
HEADER='\033[95m'
OKBLUE='\033[94m'
OKGREEN='\033[92m'
WARNING='\033[93m'
FAIL='\033[91m'
BOLD='\033[1m'
UNDERLINE='\033[4m'
ENDC='\033[0m'

echo -e "${VERMELHO}LINHA COM CORES${ENDC}"
echo -e "${HEADER}LINHA COM CORES${ENDC}"
echo -e "${OKBLUE}LINHA COM CORES${ENDC}"
echo -e "${OKGREEN}LINHA COM CORES${ENDC}"
echo -e "${WARNING}LINHA COM CORES${ENDC}"
echo -e "${FAIL}LINHA COM CORES${ENDC}"
echo -e "${BOLD}LINHA COM CORES${ENDC}"
echo -e "${UNDERLINE}LINHA COM CORES${ENDC}"
